# Generated by Django 3.2 on 2024-01-21 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(choices=[(0, '電話連絡済み'), (1, '訪問済み'), (2, '契約書送付済み'), (3, '契約済み'), (4, '失注')])),
                ('manager_checked', models.BooleanField(default=False)),
                ('memo', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesapp.customer')),
                ('staff', models.ForeignKey(limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
